version: '2'
services:
  onlyoffice-documentserver:
    #build:
    #  context: .
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=C3S6s74RFGukUXEMxLazCSpU599c6xdE
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    ports:
      - '80:80'
      - '443:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - $HOME/onlyoffice/db_onlyoffice/Data:/var/www/onlyoffice/Data
       - $HOME/onlyoffice/db_onlyoffice/logs:/var/log/onlyoffice
       - $HOME/onlyoffice/db_onlyoffice/cache/files:/var/lib/onlyoffice/documentserver/App_Data/cache/files
       - $HOME/onlyoffice/db_onlyoffice/public/files:/var/www/onlyoffice/documentserver-example/public/files
       - $HOME/onlyoffice/db_onlyoffice/fonts:/usr/share/fonts
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - $HOME/onlyoffice/db_onlyoffice/postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
